apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyGateway
gateway:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
admin:
  enablePprof: true
telemetry:
  traces:
    sink:
      type: OpenTelemetry
      openTelemetry:
        host: localhost
        protocol: grpc
        port: 19002
  metrics:
    prometheus:
      disable: false
provider:
  type: Kubernetes
extensionApis:
  enableBackend: true
logging:
  level:
    default: debug
