{
 "title": "Gateway API Comparison",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Reconciles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconcile time total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_time_seconds_sum",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Non succesful reconciles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "group by (result) (controller_runtime_reconcile_total{result!=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total reconciles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (result) (controller_runtime_reconcile_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent reconciling",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(controller_runtime_reconcile_time_seconds_sum[30s])",
     "legendFormat": "Reconcile time"
    }
   ]
  },
  { "title": "xDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "xDS snapshots created",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "xds_snapshot_create_total", "legendFormat": "Number of xDS snapshots" }
   ]
  },
  {
   "title": "xDS snapshots creation rate",
   "type": "timeseries",
   "description": "Rate of successful xDS snapshots creations",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "rate(xds_snapshot_create_total{status=\"success\"}[$__rate_interval])",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Succesful xDS snapshot creation percentage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(xds_snapshot_create_total{status=\"success\"}/(xds_snapshot_create_total{})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "xDS snapshot failiure rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(xds_snapshot_create_total{instance=\"host.docker.internal:19001\",status!=\"success\"}[$__rate_interval]))",
     "legendFormat": "Failiure rate"
    }
   ]
  },
  {
   "title": "xDS snapshots update per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "group by (nodeID) (xds_snapshot_update_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "xDS stream duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (streamID) (xds_stream_duration_seconds_bucket)",
     "legendFormat": "StreamID: {{streamID}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Memory (Control Plane)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"172.17.0.1:19001\"} /1000 / 1000",
     "legendFormat": "Virtual memory usage in MiB"
    }
   ]
  },
  {
   "title": "CPU (Control Plane)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=\"172.17.0.1:19001\"}[30s]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Publishes to watchable queues",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "targets": [
    { "expr": "watchable_publish_total{}", "legendFormat": "{{message}}" }
   ]
  },
  {
   "title": "Watchable queue length by messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum by (message) (watchable_depth{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watchable subscribe duration changes in ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum by (message) (delta(watchable_subscribe_duration_seconds_sum[1m]) * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Go Memory (Envoy)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"172.17.0.1:19001\"}",
     "legendFormat": "Allocated bytes"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"host.docker.internal:19001\"}",
     "legendFormat": "Heap allocated bytes"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"host.docker.internal:19001\"}",
     "legendFormat": "Stack inuse bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=\"host.docker.internal:19001\"}",
     "legendFormat": "Total memory obtained"
    }
   ]
  },
  {
   "title": "IDLE cpu rate (Envoy)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(go_cpu_classes_idle_cpu_seconds_total{instance=\"172.17.0.1:19001\"}[$__rate_interval]))",
     "legendFormat": "Idle cpu seconds rate"
    }
   ]
  }
 ]
}